name: native_linkify
description: Plugin which helps you to find links in String using NSDataDetector and Linkify
version: 0.0.1
homepage: https://github.com/festelo/native_linkify

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.native_linkify
        pluginClass: NativeLinkifyPlugin
      ios:
        pluginClass: NativeLinkifyPlugin
      macos:
        pluginClass: NativeLinkifyPlugin
